name: Dockerized applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      angularIMAGENAME: "${{ secrets.DOCKER_USERNAME }}/angular-app"
      nodeImageName: "${{ secrets.DOCKER_USERNAME }}/node-app"


    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # ------------------
      # Setup & Build  (Node.js)
      # ------------------
      - name: Setup Node.js (Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          working-directory: source/node-app

      - name: Install Dependencies (Node.js)
        run: npm install
        working-directory: source/node-app

      # - name: Run Lint(Node.js)
      #   run: npm run lint
      #   working-directory: source/node-app

      - name: Build Node.js
        run: npm run build
        working-directory: source/node-app

      # ------------------
      # Setup & Build Frontend (Angular)
      # ------------------
      - name: Setup Node.js (Angular)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          working-directory: source/angular-app
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Install Dependencies (Angular)
        run: npm install
        working-directory: source/angular-app

      # - name: Run Lint (Angular)
      #   run: npm run lint
      #   working-directory: source/angular-app

      - name: Build Frontend
        run: npm run build
        working-directory: source/angular-app

      # ------------------
      # Docker Build
      # ------------------
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for Node.js
        run: |
          docker build -t node-app:latest ./source/node-app
      
      - name: Docker tag for Node.js
        run: |
          docker image tag node-app:latest $nodeImageName:$BUILD_ID
      
      - name: Build Docker Image for Angular
        run: |
          docker build -t angular-app:latest ./source/angular-app
      
      - name: Docker tag for Angular
        run: |
          docker image tag node-app:latest $angularIMAGENAME:$BUILD_ID
          

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: |
          docker push $nodeImageName:$BUILD_ID
          docker push $angularIMAGENAME:$BUILD_ID

